### ISSUE TITLE
Error when exporting to google drive

### ISSUE THREAD

**Issue by bwlynch** [disinfoRG/ArticleParser#42]
When attempting to export to google drive, I'm getting the error below from running the following command: `./ap.py datapublish publication --producer 3ca261cf-d2ae-4e8d-b13c-a20c263aa800 --processed-at today --drive test --service-account service.json`. I imagine it's a slight configuration error on my part - I don't generate the error when using datapublish to publish the data locally.

```
ERROR:__main__:Traceback (most recent call last):
  File "/home/ubuntu/ArticleParser/ap-datapublish.py", line 228, in main
    full_text=args.full_text,
  File "/home/ubuntu/ArticleParser/ap-datapublish.py", line 140, in publish_to_drive
    parent_dir_id = make_parent_dir(drive, producer, exist_ok=True)
  File "/home/ubuntu/ArticleParser/ap-datapublish.py", line 54, in make_parent_dir
    if not drive.has_producer_dir(producer):
  File "/home/ubuntu/ArticleParser/articleparser/drive.py", line 59, in has_producer_dir
    return str(producer["producer_id"]) in self.data["dirs"]["producers"]
KeyError: 'dirs'
```

**Comment by pm5** [comment]
This is probably because the `data` column of a new row in the `drive` table needs to be initialized to `{"dirs": {"producers":{}}, "files": {"producers": {}}}`.  I'll probably find some time to either add this to the documentation or make a CLI command to add and edit drives...

**Comment by pm5** [comment]
Ok, I was wrong again 😂 the JSON value should be

```json
{
  "dirs": {
    "root": "<folder_id>",
    "producers": {}
  },
  "files": {
    "producers": {}
  }
}
```
 
@bwlynch I've updated the relevant [section](https://g0v.hackmd.io/OgKshAg-SFau9xm_SuZRew?view#Publish-dataset-files-to-Google-Drive) in the installation guide.  Hope that helps :)

**Comment by bwlynch** [comment]
Ha ok works now, thanks @pm5 !
